// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.4
// source: hospital.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HospitalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SourceIP string `protobuf:"bytes,1,opt,name=sourceIP,proto3" json:"sourceIP,omitempty"`
	Payload  string `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Value    *int32 `protobuf:"varint,3,opt,name=value,proto3,oneof" json:"value,omitempty"`
}

func (x *HospitalRequest) Reset() {
	*x = HospitalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hospital_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HospitalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HospitalRequest) ProtoMessage() {}

func (x *HospitalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hospital_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HospitalRequest.ProtoReflect.Descriptor instead.
func (*HospitalRequest) Descriptor() ([]byte, []int) {
	return file_hospital_proto_rawDescGZIP(), []int{0}
}

func (x *HospitalRequest) GetSourceIP() string {
	if x != nil {
		return x.SourceIP
	}
	return ""
}

func (x *HospitalRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *HospitalRequest) GetValue() int32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

type HospitalResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SourceIP string `protobuf:"bytes,1,opt,name=sourceIP,proto3" json:"sourceIP,omitempty"`
	Payload  string `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *HospitalResponse) Reset() {
	*x = HospitalResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hospital_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HospitalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HospitalResponse) ProtoMessage() {}

func (x *HospitalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hospital_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HospitalResponse.ProtoReflect.Descriptor instead.
func (*HospitalResponse) Descriptor() ([]byte, []int) {
	return file_hospital_proto_rawDescGZIP(), []int{1}
}

func (x *HospitalResponse) GetSourceIP() string {
	if x != nil {
		return x.SourceIP
	}
	return ""
}

func (x *HospitalResponse) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type ClientMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SourceIP string `protobuf:"bytes,1,opt,name=sourceIP,proto3" json:"sourceIP,omitempty"`
	Payload  string `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Value    *int32 `protobuf:"varint,3,opt,name=value,proto3,oneof" json:"value,omitempty"`
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hospital_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_hospital_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_hospital_proto_rawDescGZIP(), []int{2}
}

func (x *ClientMessage) GetSourceIP() string {
	if x != nil {
		return x.SourceIP
	}
	return ""
}

func (x *ClientMessage) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *ClientMessage) GetValue() int32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

type HospitalListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SourceIP string   `protobuf:"bytes,1,opt,name=sourceIP,proto3" json:"sourceIP,omitempty"`
	SList    []string `protobuf:"bytes,2,rep,name=s_list,json=sList,proto3" json:"s_list,omitempty"`
}

func (x *HospitalListReq) Reset() {
	*x = HospitalListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hospital_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HospitalListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HospitalListReq) ProtoMessage() {}

func (x *HospitalListReq) ProtoReflect() protoreflect.Message {
	mi := &file_hospital_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HospitalListReq.ProtoReflect.Descriptor instead.
func (*HospitalListReq) Descriptor() ([]byte, []int) {
	return file_hospital_proto_rawDescGZIP(), []int{3}
}

func (x *HospitalListReq) GetSourceIP() string {
	if x != nil {
		return x.SourceIP
	}
	return ""
}

func (x *HospitalListReq) GetSList() []string {
	if x != nil {
		return x.SList
	}
	return nil
}

type HospitalListRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SourceIP string   `protobuf:"bytes,1,opt,name=sourceIP,proto3" json:"sourceIP,omitempty"`
	SList    []string `protobuf:"bytes,2,rep,name=s_list,json=sList,proto3" json:"s_list,omitempty"`
	Err      *string  `protobuf:"bytes,3,opt,name=err,proto3,oneof" json:"err,omitempty"`
}

func (x *HospitalListRes) Reset() {
	*x = HospitalListRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hospital_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HospitalListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HospitalListRes) ProtoMessage() {}

func (x *HospitalListRes) ProtoReflect() protoreflect.Message {
	mi := &file_hospital_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HospitalListRes.ProtoReflect.Descriptor instead.
func (*HospitalListRes) Descriptor() ([]byte, []int) {
	return file_hospital_proto_rawDescGZIP(), []int{4}
}

func (x *HospitalListRes) GetSourceIP() string {
	if x != nil {
		return x.SourceIP
	}
	return ""
}

func (x *HospitalListRes) GetSList() []string {
	if x != nil {
		return x.SList
	}
	return nil
}

func (x *HospitalListRes) GetErr() string {
	if x != nil && x.Err != nil {
		return *x.Err
	}
	return ""
}

type PeerPing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SourceIP      string  `protobuf:"bytes,1,opt,name=sourceIP,proto3" json:"sourceIP,omitempty"`
	DestinationIP string  `protobuf:"bytes,2,opt,name=destinationIP,proto3" json:"destinationIP,omitempty"`
	Payload       *string `protobuf:"bytes,3,opt,name=payload,proto3,oneof" json:"payload,omitempty"`
}

func (x *PeerPing) Reset() {
	*x = PeerPing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hospital_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PeerPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerPing) ProtoMessage() {}

func (x *PeerPing) ProtoReflect() protoreflect.Message {
	mi := &file_hospital_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerPing.ProtoReflect.Descriptor instead.
func (*PeerPing) Descriptor() ([]byte, []int) {
	return file_hospital_proto_rawDescGZIP(), []int{5}
}

func (x *PeerPing) GetSourceIP() string {
	if x != nil {
		return x.SourceIP
	}
	return ""
}

func (x *PeerPing) GetDestinationIP() string {
	if x != nil {
		return x.DestinationIP
	}
	return ""
}

func (x *PeerPing) GetPayload() string {
	if x != nil && x.Payload != nil {
		return *x.Payload
	}
	return ""
}

type PingEcho struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SourceIP string  `protobuf:"bytes,1,opt,name=sourceIP,proto3" json:"sourceIP,omitempty"`
	Payload  *string `protobuf:"bytes,2,opt,name=payload,proto3,oneof" json:"payload,omitempty"`
}

func (x *PingEcho) Reset() {
	*x = PingEcho{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hospital_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingEcho) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingEcho) ProtoMessage() {}

func (x *PingEcho) ProtoReflect() protoreflect.Message {
	mi := &file_hospital_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingEcho.ProtoReflect.Descriptor instead.
func (*PingEcho) Descriptor() ([]byte, []int) {
	return file_hospital_proto_rawDescGZIP(), []int{6}
}

func (x *PingEcho) GetSourceIP() string {
	if x != nil {
		return x.SourceIP
	}
	return ""
}

func (x *PingEcho) GetPayload() string {
	if x != nil && x.Payload != nil {
		return *x.Payload
	}
	return ""
}

var File_hospital_proto protoreflect.FileDescriptor

var file_hospital_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x68, 0x6f, 0x73, 0x70, 0x69, 0x74, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x68, 0x6f, 0x73, 0x70, 0x69, 0x74, 0x61, 0x6c, 0x22, 0x6c, 0x0a, 0x0f, 0x48, 0x6f,
	0x73, 0x70, 0x69, 0x74, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x50, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x50, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x12, 0x19, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x48, 0x00, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x88, 0x01, 0x01, 0x42, 0x08,
	0x0a, 0x06, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x48, 0x0a, 0x10, 0x48, 0x6f, 0x73, 0x70,
	0x69, 0x74, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x50, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x50, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x22, 0x6a, 0x0a, 0x0d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x50, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x50, 0x12,
	0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x19, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x44,
	0x0a, 0x0f, 0x48, 0x6f, 0x73, 0x70, 0x69, 0x74, 0x61, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x50, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x50, 0x12, 0x15, 0x0a,
	0x06, 0x73, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x73,
	0x4c, 0x69, 0x73, 0x74, 0x22, 0x63, 0x0a, 0x0f, 0x48, 0x6f, 0x73, 0x70, 0x69, 0x74, 0x61, 0x6c,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x49, 0x50, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x49, 0x50, 0x12, 0x15, 0x0a, 0x06, 0x73, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x05, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x03, 0x65, 0x72,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x03, 0x65, 0x72, 0x72, 0x88, 0x01,
	0x01, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x65, 0x72, 0x72, 0x22, 0x77, 0x0a, 0x08, 0x50, 0x65, 0x65,
	0x72, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49,
	0x50, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49,
	0x50, 0x12, 0x24, 0x0a, 0x0d, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x49, 0x50, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x50, 0x12, 0x1d, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x88, 0x01, 0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x70, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x22, 0x51, 0x0a, 0x08, 0x50, 0x69, 0x6e, 0x67, 0x45, 0x63, 0x68, 0x6f, 0x12, 0x1a,
	0x0a, 0x08, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x50, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x50, 0x12, 0x1d, 0x0a, 0x07, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x70,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x88, 0x01, 0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x32, 0xa3, 0x01, 0x0a, 0x08, 0x48, 0x6f, 0x73, 0x70, 0x69, 0x74,
	0x61, 0x6c, 0x12, 0x49, 0x0a, 0x0e, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x6f, 0x48, 0x6f, 0x73, 0x70,
	0x69, 0x74, 0x61, 0x6c, 0x12, 0x19, 0x2e, 0x68, 0x6f, 0x73, 0x70, 0x69, 0x74, 0x61, 0x6c, 0x2e,
	0x48, 0x6f, 0x73, 0x70, 0x69, 0x74, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1a, 0x2e, 0x68, 0x6f, 0x73, 0x70, 0x69, 0x74, 0x61, 0x6c, 0x2e, 0x48, 0x6f, 0x73, 0x70, 0x69,
	0x74, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4c, 0x0a,
	0x12, 0x53, 0x65, 0x6e, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x6f, 0x48, 0x6f, 0x73, 0x70, 0x69,
	0x74, 0x61, 0x6c, 0x12, 0x19, 0x2e, 0x68, 0x6f, 0x73, 0x70, 0x69, 0x74, 0x61, 0x6c, 0x2e, 0x48,
	0x6f, 0x73, 0x70, 0x69, 0x74, 0x61, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x19,
	0x2e, 0x68, 0x6f, 0x73, 0x70, 0x69, 0x74, 0x61, 0x6c, 0x2e, 0x48, 0x6f, 0x73, 0x70, 0x69, 0x74,
	0x61, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x22, 0x00, 0x32, 0x7a, 0x0a, 0x04, 0x50,
	0x65, 0x65, 0x72, 0x12, 0x40, 0x0a, 0x0a, 0x53, 0x65, 0x6e, 0x64, 0x54, 0x6f, 0x50, 0x65, 0x65,
	0x72, 0x12, 0x17, 0x2e, 0x68, 0x6f, 0x73, 0x70, 0x69, 0x74, 0x61, 0x6c, 0x2e, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x17, 0x2e, 0x68, 0x6f, 0x73,
	0x70, 0x69, 0x74, 0x61, 0x6c, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x22, 0x00, 0x12, 0x30, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x12, 0x2e,
	0x68, 0x6f, 0x73, 0x70, 0x69, 0x74, 0x61, 0x6c, 0x2e, 0x50, 0x65, 0x65, 0x72, 0x50, 0x69, 0x6e,
	0x67, 0x1a, 0x12, 0x2e, 0x68, 0x6f, 0x73, 0x70, 0x69, 0x74, 0x61, 0x6c, 0x2e, 0x50, 0x69, 0x6e,
	0x67, 0x45, 0x63, 0x68, 0x6f, 0x22, 0x00, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4c, 0x79, 0x73, 0x65, 0x74, 0x73, 0x44, 0x61, 0x6c, 0x2f,
	0x68, 0x6f, 0x73, 0x70, 0x69, 0x74, 0x61, 0x6c, 0x5f, 0x73, 0x65, 0x63, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hospital_proto_rawDescOnce sync.Once
	file_hospital_proto_rawDescData = file_hospital_proto_rawDesc
)

func file_hospital_proto_rawDescGZIP() []byte {
	file_hospital_proto_rawDescOnce.Do(func() {
		file_hospital_proto_rawDescData = protoimpl.X.CompressGZIP(file_hospital_proto_rawDescData)
	})
	return file_hospital_proto_rawDescData
}

var file_hospital_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_hospital_proto_goTypes = []interface{}{
	(*HospitalRequest)(nil),  // 0: hospital.HospitalRequest
	(*HospitalResponse)(nil), // 1: hospital.HospitalResponse
	(*ClientMessage)(nil),    // 2: hospital.ClientMessage
	(*HospitalListReq)(nil),  // 3: hospital.HospitalListReq
	(*HospitalListRes)(nil),  // 4: hospital.HospitalListRes
	(*PeerPing)(nil),         // 5: hospital.PeerPing
	(*PingEcho)(nil),         // 6: hospital.PingEcho
}
var file_hospital_proto_depIdxs = []int32{
	0, // 0: hospital.Hospital.SendToHospital:input_type -> hospital.HospitalRequest
	3, // 1: hospital.Hospital.SendListToHospital:input_type -> hospital.HospitalListReq
	2, // 2: hospital.Peer.SendToPeer:input_type -> hospital.ClientMessage
	5, // 3: hospital.Peer.Ping:input_type -> hospital.PeerPing
	1, // 4: hospital.Hospital.SendToHospital:output_type -> hospital.HospitalResponse
	4, // 5: hospital.Hospital.SendListToHospital:output_type -> hospital.HospitalListRes
	2, // 6: hospital.Peer.SendToPeer:output_type -> hospital.ClientMessage
	6, // 7: hospital.Peer.Ping:output_type -> hospital.PingEcho
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hospital_proto_init() }
func file_hospital_proto_init() {
	if File_hospital_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_hospital_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HospitalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hospital_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HospitalResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hospital_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hospital_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HospitalListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hospital_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HospitalListRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hospital_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PeerPing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hospital_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingEcho); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_hospital_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_hospital_proto_msgTypes[2].OneofWrappers = []interface{}{}
	file_hospital_proto_msgTypes[4].OneofWrappers = []interface{}{}
	file_hospital_proto_msgTypes[5].OneofWrappers = []interface{}{}
	file_hospital_proto_msgTypes[6].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hospital_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_hospital_proto_goTypes,
		DependencyIndexes: file_hospital_proto_depIdxs,
		MessageInfos:      file_hospital_proto_msgTypes,
	}.Build()
	File_hospital_proto = out.File
	file_hospital_proto_rawDesc = nil
	file_hospital_proto_goTypes = nil
	file_hospital_proto_depIdxs = nil
}
